tinyMCE.addI18n('de.celimage_dlg', {
  "image_list" : "Bilderliste",
  "align_right" : "Rechts",
  "align_left" : "Links",
  "align_textbottom" : "Unten im Text",
  "align_texttop" : "Oben im Text",
  "align_bottom" : "Unten",
  "align_middle" : "Mittig",
  "align_top" : "Oben",
  "align_baseline" : "Zeile",
  align : "Ausrichtung",
  hspace : "Horizontaler Abstand",
  vspace : "Vertikaler Abstand",
  dimensions : "Ausma\u00dfe",
  border : "Rahmen",
  list : "Bilderliste",
  alt : "Beschreibung",
  src : "Adresse",
  "dialog_title" : "Bild einf\u00fcgen/ver\u00e4ndern",
  "missing_alt" : "Wollen Sie wirklich keine Beschreibung eingeben? Bestimmte Benutzer mit k\u00f6rperlichen Einschr\u00e4nkungen k\u00f6nnen so nicht darauf zugreifen, ebenso solche, die einen Textbrowser benutzen oder die Anzeige von Bildern deaktiviert haben.",
  "example_img" : "Vorschau auf das Aussehen",
  misc : "Verschiedenes",
  mouseout : "bei keinem Mauskontakt",
  mouseover : "bei Mauskontakt",
  "alt_image" : "Alternatives Bild",
  "swap_image" : "Bild austauschen",
  map : "Image-Map",
  id : "ID",
  rtl : "Rechts nach links",
  ltr : "Links nach rechts",
  classes : "Klassen",
  style : "Format",
  "long_desc" : "Ausf\u00fchrliche Beschreibung",
  langcode : "Sprachcode",
  langdir : "Schriftrichtung",
  "constrain_proportions" : "Seitenverh\u00e4ltnis beibehalten",
  preview : "Vorschau",
  title : "Titel",
  imageDetails : "Vorschau",
  "tab_advanced" : "Erweitert",
  "tab_appearance" : "Aussehen",
  "tab_imageDetails" : "Vorschau",
  "tab_animation" :"Animation",
  "tab_imagePicker" : "Picker",
  slideshow : "Bildstrecke",
  hasSlideshow : "mit Bildstrecke",
  hasAutoChange : "Automatischer Bildwechsel",
  'hasAutoChange_auto_start' : "automatischer Start",
  'hasAutoChange_manuel_start' : "Manuell Starten",
  'hasAutoChange_none' : "kein",
  'addCounter' : "Zähler",
  'addCounter_none' : "kein",
  'addCounter_normal' : "normal",
  'addCounter_leadingzeros' : "führende Nullen",
  isSlideshowRandomStart : "Zuf\u00e4lliger Startpunkt",
  isSlideshowCustomStart : "Eigenes Standbild",
  hasSlideshowAddNavigation : "Navigation hinzuf\u00fcgen",
  gallery : "Bild Album",
  "galleryPicker" : "Bildstrecke",
  "slideshowFixStartImageNum" : "feste Startbild Nummer",
  delay : "Bildwechsel nach (Sekunden)",
  defaultEffect : "standard (Fade)",
  effects : "Bildwechsel Effekt",
  "imagePicker" : "Bildauswahl",
  "select_image_first" : "Bitte zuerst Bild ausw&auml;len.",
  "uploadImage" : "Bild hochladen",
  "overlay" : "Bild in Overlay",
  "hasOverlay" : "Bild bei Klick in Overlay öffnen",
  "hasCloseButton" : "Schliessen button hinzufügen",
  "tab_crop" : "Ausschnitt",
  "fitToScreen" : "Original zoomen:",
  "cropX" : "Startpunkt",
  "cropWidth" : "Auswahldimension",
  "asp_ratio" : "Seitenverhältnis",
  "asp_ratio_fix" : "Fixieren",
  "asp_ratio_ratio" : "Seitenverhältnis",
  "release" : "Ganzes Bild",
  "exec" : "Anwenden",
  "resetMax" : "Zurücksetzen"
});