import '@/assets/main.css';

import App from '@/App.vue';
import { useAuthStore } from '@/core/stores/auth';
import { createI18n } from '@/plugins/i18n';
import { createAuthPlugin } from '@/plugins/plugin.auth';
import Store from '@/plugins/plugin.pinia';
import { createVueDompurify } from '@/plugins/vueDompurify';
import { useLogger } from '@/utils/logger';
import { createApp } from 'vue';
import VueMatomo, { type MatomoOptions } from 'vue-matomo';

const logger = useLogger('Helvetia-Alumni');

const app = createApp(App);
app.config.errorHandler = (err, instance, info) => {
  logger.error(err as string, instance, info);
};

app.use(Store);

// register auth plugin with router and store
const authStore = useAuthStore();

const locale = import.meta.env.VITE_DEFAULT_LOCALE;

const matomoConfig: MatomoOptions = {
  host: '//synstat.srv-inter.net',
  siteId: '5',
  enableLinkTracking: true,
};

app.use(createI18n({ locale }));
app.use(Auth);
app.use(createVueDompurify);
app.use(VueMatomo, matomoConfig);

const localDev = (import.meta.env.VITE_ENABLE_LOCAL_DEVELOPMENT ?? 'true') === 'true';
app.provide('localDev', localDev);
if (localDev) {
  logger.info('local development enabled');
}

logger.debug('mounting app...');
app.mount('#app');

// Extend Window interface for Matomo, typing generated by Copilot
declare global {
  interface Window {
    _paq: Array<string | string[]>;
  }
}

window._paq.push(['trackPageView']); //To track pageview
logger.info('main ready');
