#           _                           _        #
#   ___ ___| | ___ _ __ ___   ___ _ __ | |_ ___  #
#  / __/ _ \ |/ _ \ '_ ` _ \ / _ \ '_ \| __/ __| #
# | (_|  __/ |  __/ | | | | |  __/ | | | |_\__ \ #
#  \___\___|_|\___|_| |_| |_|\___|_| |_|\__|___/ #
#                                                #

FROM tomcat:9-jdk11-temurin

# when using docker compose, these ENV values may be overridden from the .env file
ENV CELEMENTS_DATA=/usr/local/celements
# add tomcat jpda debugging environmental variables
# ENV JPDA_OPTS="-agentlib:jdwp=transport=dt_socket,address=8000,server=y,suspend=n"
ENV JPDA_ADDRESS="8000"
ENV JPDA_TRANSPORT="dt_socket"

# copy configurations / scripts
COPY docker/tomcat /usr/local/config

# TODO ENV CATALINA_OPTS="-Dkey=value" working?

# installs and setup
RUN mkdir -p \
${CELEMENTS_DATA} \
${CATALINA_HOME}/temp \
&& cp /usr/local/config/setenv.sh ${CATALINA_HOME}/bin/

# define custom command (with remote debugging)
CMD ["catalina.sh", "jpda", "run"]
