#           _                           _        #
#   ___ ___| | ___ _ __ ___   ___ _ __ | |_ ___  #
#  / __/ _ \ |/ _ \ '_ ` _ \ / _ \ '_ \| __/ __| #
# | (_|  __/ |  __/ | | | | |  __/ | | | |_\__ \ #
#  \___\___|_|\___|_| |_| |_|\___|_| |_|\__|___/ #
#                                                #

FROM tomcat:9-jdk11-temurin

# environment variables, may be overridden from the .env file
# celements
ENV CELEMENTS_DATA=/usr/local/celements
# tomcat
ENV CATALINA_XMX="2g"
# tomcat jpda debugging
ENV JPDA_ADDRESS="8000"
ENV JPDA_TRANSPORT="dt_socket"

# copy configurations / scripts
COPY docker/tomcat /usr/local/config

# installs and setup
RUN mkdir -p \
${CELEMENTS_DATA} \
${CATALINA_HOME}/temp \
&& cp /usr/local/config/setenv.sh ${CATALINA_HOME}/bin/

# define custom command (with remote debugging)
CMD ["catalina.sh", "jpda", "run"]
