FROM tomcat:9-jdk11-temurin
#           _                           _       
#   ___ ___| | ___ _ __ ___   ___ _ __ | |_ ___ 
#  / __/ _ \ |/ _ \ '_ ` _ \ / _ \ '_ \| __/ __|
# | (_|  __/ |  __/ | | | | |  __/ | | | |_\__ \
#  \___\___|_|\___|_| |_| |_|\___|_| |_|\__|___/
#

# when using docker-compose, these ENV values may be overridden from the .env file
ENV CELEMENTS_DATA=/usr/local/celements

# Install tools and JDBC connector
RUN apt-get update && \
  apt-get --no-install-recommends -y install \
    unzip \
    libmariadb-java && \
  rm -rf /var/lib/apt/lists/*

COPY target/celements-web.war ./

# Deploy Celements as the ROOT webapp in Tomcat
# Create the Tomcat temporary and Lucene permanent directory
RUN rm -rf ${CATALINA_HOME}/webapps/* && \
  unzip -d ${CATALINA_HOME}/webapps/ROOT celements-web.war && \
  rm -f celements-web.war

# TODO create mount point for volume with application
# RUN mkdir $CATALINA_HOME/webapps/ROOT

# Create required dirs and copy the JDBC driver in the Tomcat lib
RUN mkdir -p ${CELEMENTS_DATA} ${CATALINA_HOME}/temp

# Configure Tomcat
COPY setenv.sh ${CATALINA_HOME}/bin/
# ENV CATALINA_OPTS="-Dkey=value" working?

# Setup the Hibernate configuration
# TODO this is already done when building the war, should it be changable at this point?
# COPY hibernate.cfg.xml /usr/local/tomcat/webapps/ROOT/WEB-INF/hibernate.cfg.xml

# start tomcat (with remote debugging)
CMD ["catalina.sh", "jpda", "run"]
