#           _                           _        #
#   ___ ___| | ___ _ __ ___   ___ _ __ | |_ ___  #
#  / __/ _ \ |/ _ \ '_ ` _ \ / _ \ '_ \| __/ __| #
# | (_|  __/ |  __/ | | | | |  __/ | | | |_\__ \ #
#  \___\___|_|\___|_| |_| |_|\___|_| |_|\__|___/ #
#                                                #

FROM tomcat:10-jdk21-temurin

# environment variables, may be overridden from the .env file
# celements
ENV CELEMENTS_DATA=/usr/local/celements
ENV CONF_DIR=/usr/local/conf
# tomcat
ENV CATALINA_XMX="2g"
# tomcat jpda debugging
ENV JPDA_ADDRESS="8000"
ENV JPDA_TRANSPORT="dt_socket"

# copy configurations
COPY docker/tomcat/conf ${CONF_DIR}

# installs and setup
RUN mkdir -p \
    ${CELEMENTS_DATA} \
    ${CATALINA_HOME}/temp \
    ${CATALINA_HOME}/conf/Catalina/localhost \
  && cp ${CONF_DIR}/setenv.sh ${CATALINA_HOME}/bin/ \
  && cp ${CONF_DIR}/jakarta.converter.xml ${CATALINA_HOME}/conf/Catalina/localhost/ROOT.xml

# define custom command (with remote debugging)
CMD ["catalina.sh", "jpda", "run"]
