name: ${APP_NAME}
services:

  web:
    image: ghcr.io/synventis-infra/tomcat:release
    ports:
      - "${TOMCAT_PORT:-2080}:8080" # tomcat
      - "${JPDA_PORT:-2000}:8000" # remote debugging
    env_file:
      - .env
      - .env.tomcat
    volumes:
      - web-data:${APP_DATA}:rw
      - ./target/${APP_NAME}-web:/usr/local/tomcat/webapps/ROOT:ro
      - ./docker/tomcat/log4j2.properties:/usr/local/tomcat/webapps/ROOT/WEB-INF/classes/log4j2.properties:ro
    restart: unless-stopped
    logging:
      driver: journald
    depends_on:
      - db

  db:
    image: mariadb:10.1
    ports:
      - "${DB_HOST_PORT:-2306}:3306" # for direct client access
    env_file: .env
    environment:
      - "MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD:?}"
    volumes:
      - db-data:/var/lib/mysql
      - ./docker/mariadb/mysql.cnf:/etc/mysql/conf.d/mysql.cnf:ro
      - ./docker/mariadb/init:/docker-entrypoint-initdb.d:ro
    restart: unless-stopped
    logging:
      driver: journald

volumes:
  web-data:
  db-data:
