name: celements-web
services:

  webserver:
    container_name: celements-web
    image: ghcr.io/synventis-infra/tomcat:release
    ports:
      - "${TOMCAT_PORT:-2080}:8080" # tomcat
      - "${JPDA_PORT:-2000}:8000" # remote debugging
    env_file: .env
    volumes:
      - ./target/celements-web:/usr/local/tomcat/webapps/ROOT:ro
      - ./docker/tomcat/log4j2.properties:/usr/local/tomcat/webapps/ROOT/WEB-INF/classes/log4j2.properties:ro
    restart: unless-stopped
    networks:
      - celements
    logging:
      driver: journald
    depends_on:
      - sqlserver

  sqlserver:
    container_name: celements-db
    image: mariadb:10.1
    ports:
      - "${DB_HOST_PORT:-2306}:3306" # for direct client access
    env_file: .env
    environment:
      - "MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD:?}"
    volumes:
      - db-data:/var/lib/mysql
      - ./docker/sqlserver/mysql.cnf:/etc/mysql/conf.d/mysql.cnf:ro
      - ./docker/sqlserver/init:/docker-entrypoint-initdb.d:ro
    restart: unless-stopped
    networks:
      - celements
    logging:
      driver: journald

volumes:
  db-data:

networks:
  celements:
    driver: bridge
