<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
  <url>https://github.com/celements/celements-web</url>
  <parent>
    <groupId>com.celements</groupId>
    <artifactId>celements-parent</artifactId>
    <version>7.1-SNAPSHOT</version>
  </parent>
  <modelVersion>4.0.0</modelVersion>
  <artifactId>celements-web</artifactId>
  <version>7.1-SNAPSHOT</version>
  <packaging>war</packaging>
  <name>Celements Webapplication</name>
  <licenses>
    <license>
      <name>LGPL 2.1</name>
      <url>http://www.gnu.org/licenses/old-licenses/lgpl-2.1.html</url>
      <distribution>repo</distribution>
    </license>
  </licenses>
  <scm>
    <connection>scm:git:git://github.com/celements/celements-web</connection>
    <developerConnection>scm:git:git@github.com:celements/celements-web.git</developerConnection>
    <url>https://github.com/celements/celements-web</url>
    <tag>HEAD</tag>
  </scm>
  <properties>
    <catalina.port>10081</catalina.port>
    <catalina.home>${env.CATALINA_HOME}</catalina.home>
    <xwiki.cfg.xwiki.db>main</xwiki.cfg.xwiki.db>
    <xwiki.cfg.xwiki.db.prefix />
    <xwiki.cfg.xwiki.url.protocol>http</xwiki.cfg.xwiki.url.protocol>
    <hibernate.cfg.xml.connection.scheme>jdbc:mysql</hibernate.cfg.xml.connection.scheme>
    <hibernate.cfg.xml.connection.host>localhost</hibernate.cfg.xml.connection.host>
    <hibernate.cfg.xml.connection.port />
    <hibernate.cfg.xml.connection.query>
      ?useServerPrepStmts=false&amp;amp;useUnicode=true&amp;amp;characterEncoding=UTF-8&amp;amp;sessionVariables=sql_mode=''&amp;amp;usePipelineAuth=false&amp;amp;disablePipeline=true</hibernate.cfg.xml.connection.query>
    <hibernate.cfg.xml.connection.url>
      ${hibernate.cfg.xml.connection.scheme}://${hibernate.cfg.xml.connection.host}${hibernate.cfg.xml.connection.port}/${xwiki.cfg.xwiki.db.prefix}${xwiki.cfg.xwiki.db}${hibernate.cfg.xml.connection.query}</hibernate.cfg.xml.connection.url>
    <hibernate.cfg.xml.connection.username>xwiki</hibernate.cfg.xml.connection.username>
    <hibernate.cfg.xml.connection.password>xwiki</hibernate.cfg.xml.connection.password>
    <hibernate.cfg.xml.connection.driver_class>com.mysql.jdbc.Driver</hibernate.cfg.xml.connection.driver_class>
    <hibernate.cfg.xml.dialect>com.celements.query.CelMySQLDialect</hibernate.cfg.xml.dialect>
    <hibernate.cfg.xml.connection.provider_class>com.xpn.xwiki.store.DBCPConnectionProvider</hibernate.cfg.xml.connection.provider_class>
    <hibernate.cfg.xml.connection.pool_size>2</hibernate.cfg.xml.connection.pool_size>
    <hibernate.cfg.xml.statement_cache.size>2</hibernate.cfg.xml.statement_cache.size>
    <log4j.properties.monitorInterval>60</log4j.properties.monitorInterval>
    <log4j.properties.logger.config />
  </properties>
  <dependencies>
    <dependency>
      <groupId>javax.servlet</groupId>
      <artifactId>javax.servlet-api</artifactId>
      <scope>provided</scope>
    </dependency>
    <dependency>
      <groupId>org.apache.logging.log4j</groupId>
      <artifactId>log4j-web</artifactId>
    </dependency>
    <dependency>
      <groupId>org.slf4j</groupId>
      <artifactId>slf4j-api</artifactId>
    </dependency>
    <dependency>
      <groupId>org.slf4j</groupId>
      <artifactId>jul-to-slf4j</artifactId>
    </dependency>
    <dependency>
      <groupId>org.slf4j</groupId>
      <artifactId>jcl-over-slf4j</artifactId>
    </dependency>

    <!-- xwiki platform dependencies -->
    <!-- START xwiki-enterprise-web war -->
    <!-- START xwiki-web-standard war -->
    <!-- Captcha component -->
    <dependency>
      <groupId>org.xwiki.platform</groupId>
      <artifactId>xwiki-core-captcha</artifactId>
    </dependency>
    <!-- Crypto Module -->
    <dependency>
      <groupId>org.xwiki.platform</groupId>
      <artifactId>xwiki-core-crypto</artifactId>
    </dependency>
    <!-- CSRF protection -->
    <dependency>
      <groupId>org.xwiki.platform</groupId>
      <artifactId>xwiki-core-csrf</artifactId>
    </dependency>
    <!-- END xwiki-web-standard war -->
    <dependency>
      <groupId>com.celements</groupId>
      <artifactId>celements-scheduler</artifactId>
    </dependency>
    <dependency>
      <groupId>com.celements</groupId>
      <artifactId>celements-mailsender</artifactId>
    </dependency>
    <dependency>
      <groupId>org.xwiki.platform</groupId>
      <artifactId>xwiki-platform-tag-api</artifactId>
    </dependency>
    <!-- END xwiki-enterprise-web war -->
    <dependency>
      <groupId>com.xpn.xwiki.platform.plugins</groupId>
      <artifactId>xwiki-plugin-wiki-manager</artifactId>
    </dependency>
    <dependency>
      <!-- [CELDEV-1013] required by xwiki-plugin-wiki-manager -->
      <groupId>org.codehaus.plexus</groupId>
      <artifactId>plexus-utils</artifactId>
      <version>3.0.24</version>
    </dependency>
    <!-- celements module-web dependencies -->
    <dependency>
      <groupId>com.celements</groupId>
      <artifactId>blog-web</artifactId>
      <type>war</type>
    </dependency>
    <dependency>
      <groupId>com.celements</groupId>
      <artifactId>calendar-web</artifactId>
      <type>war</type>
    </dependency>
    <dependency>
      <groupId>com.celements</groupId>
      <artifactId>image-web</artifactId>
      <type>war</type>
    </dependency>
    <dependency>
      <groupId>com.celements</groupId>
      <artifactId>tinymce-langs</artifactId>
      <version>3.4.3.2-celRTE-b3-SNAPSHOT</version>
      <type>war</type>
    </dependency>
    <dependency>
      <groupId>com.celements</groupId>
      <artifactId>tinymce-langs-v4</artifactId>
      <type>war</type>
    </dependency>
    <dependency>
      <groupId>com.celements</groupId>
      <artifactId>tinymce-langs-v6</artifactId>
      <type>war</type>
    </dependency>
    <dependency>
      <groupId>com.celements</groupId>
      <artifactId>celements-richtext-web</artifactId>
      <type>war</type>
    </dependency>
    <dependency>
      <groupId>com.xpn.xwiki.platform.plugins</groupId>
      <artifactId>xwiki-plugin-application-manager</artifactId>
    </dependency>
    <dependency>
      <groupId>com.celements</groupId>
      <artifactId>celements-wiki-manager-web</artifactId>
      <type>war</type>
    </dependency>
    <dependency>
      <groupId>com.celements</groupId>
      <artifactId>celements-user-manager-web</artifactId>
      <type>war</type>
    </dependency>
    <dependency>
      <groupId>com.celements</groupId>
      <artifactId>celements-layout-web</artifactId>
      <type>war</type>
    </dependency>

    <!-- celements dependencies -->
    <dependency>
      <groupId>com.celements</groupId>
      <artifactId>celements-commons</artifactId>
    </dependency>
    <dependency>
      <groupId>com.celements</groupId>
      <artifactId>celements-xwiki-core</artifactId>
    </dependency>
    <dependency>
      <groupId>com.celements</groupId>
      <artifactId>celements-xwiki-velocity</artifactId>
    </dependency>
    <dependency>
      <groupId>com.celements</groupId>
      <artifactId>celements-xwiki-rendering-api</artifactId>
    </dependency>
    <dependency>
      <groupId>com.celements</groupId>
      <artifactId>celements-xwiki-xml</artifactId>
    </dependency>
    <dependency>
      <groupId>com.celements</groupId>
      <artifactId>celements-global-redirect</artifactId>
    </dependency>
    <dependency>
      <groupId>com.celements</groupId>
      <artifactId>celements-component</artifactId>
    </dependency>
    <dependency>
      <groupId>com.celements</groupId>
      <artifactId>celements-reference</artifactId>
    </dependency>
    <dependency>
      <groupId>com.celements</groupId>
      <artifactId>celements-observation</artifactId>
    </dependency>
    <dependency>
      <groupId>com.celements</groupId>
      <artifactId>celements-servlet</artifactId>
    </dependency>
    <dependency>
      <groupId>com.celements</groupId>
      <artifactId>celements-config-source-api</artifactId>
    </dependency>
    <dependency>
      <groupId>com.celements</groupId>
      <artifactId>celements-config-source</artifactId>
    </dependency>
    <dependency>
      <groupId>com.celements</groupId>
      <artifactId>celements-model</artifactId>
    </dependency>
    <dependency>
      <groupId>com.celements</groupId>
      <artifactId>celements-core</artifactId>
    </dependency>
    <dependency>
      <groupId>com.celements</groupId>
      <artifactId>celements-search</artifactId>
    </dependency>
    <dependency>
      <groupId>com.celements</groupId>
      <artifactId>celements-captcha</artifactId>
    </dependency>
    <dependency>
      <groupId>com.celements</groupId>
      <artifactId>celements-subsystem-migration-manager</artifactId>
    </dependency>
    <dependency>
      <groupId>com.celements</groupId>
      <artifactId>celements-spring-mvc</artifactId>
    </dependency>
    <dependency>
      <groupId>com.celements</groupId>
      <artifactId>celements-messages-web</artifactId>
      <type>war</type>
    </dependency>
    <dependency>
      <groupId>com.celements</groupId>
      <artifactId>celements-spring-security</artifactId>
    </dependency>
    <dependency>
      <groupId>com.celements</groupId>
      <artifactId>celements-keycloak</artifactId>
    </dependency>
    <dependency>
      <groupId>com.celements</groupId>
      <artifactId>celements-filebase</artifactId>
    </dependency>

    <!-- Spring -->
    <dependency>
      <groupId>org.springframework</groupId>
      <artifactId>spring-context</artifactId>
    </dependency>
    <dependency>
      <groupId>org.springframework</groupId>
      <artifactId>spring-web</artifactId>
    </dependency>
    <dependency>
      <groupId>org.springframework</groupId>
      <artifactId>spring-webmvc</artifactId>
    </dependency>
    <dependency>
      <groupId>org.springframework.kafka</groupId>
      <artifactId>spring-kafka</artifactId>
    </dependency>
    <!-- other dependencies -->
    <dependency>
      <groupId>xalan</groupId>
      <artifactId>xalan</artifactId>
    </dependency>
    <!-- Dom4J & Css4J [CELDEV-927] -->
    <dependency>
      <groupId>org.dom4j</groupId>
      <artifactId>dom4j</artifactId>
    </dependency>
    <dependency>
      <groupId>jaxen</groupId>
      <artifactId>jaxen</artifactId>
    </dependency>
    <dependency>
      <groupId>io.sf.carte</groupId>
      <artifactId>css4j</artifactId>
    </dependency>
    <dependency>
      <groupId>io.sf.carte</groupId>
      <artifactId>css4j-dom4j</artifactId>
    </dependency>
    <dependency>
      <groupId>org.jsoup</groupId>
      <artifactId>jsoup</artifactId>
    </dependency>
    <!-- JAX-RS implementation -->
    <dependency>
      <groupId>org.glassfish.jersey.core</groupId>
      <artifactId>jersey-common</artifactId>
    </dependency>
    <dependency>
      <groupId>javax.ws.rs</groupId>
      <artifactId>javax.ws.rs-api</artifactId>
    </dependency>
    <!-- hibernate annotations needed for org.hibernate.type.EnumType -->
    <dependency>
      <groupId>org.hibernate</groupId>
      <artifactId>hibernate-annotations</artifactId>
    </dependency>
    <dependency>
      <groupId>org.reflections</groupId>
      <artifactId>reflections</artifactId>
      <version>0.9.12</version>
      <exclusions>
        <!-- [CELDEV-808] exclude xml-apis compile dependency -->
        <exclusion>
          <groupId>xml-apis</groupId>
          <artifactId>xml-apis</artifactId>
        </exclusion>
      </exclusions>
    </dependency>

    <!-- JDBC connector -->
    <dependency>
      <groupId>mysql</groupId>
      <artifactId>mysql-connector-java</artifactId>
    </dependency>

  </dependencies>
  <dependencyManagement>
    <dependencies>
      <!-- Force the newer JTA for old Hibernate transitive -->
      <dependency>
        <groupId>javax.transaction</groupId>
        <artifactId>jta</artifactId>
        <version>1.1</version>
      </dependency>
    </dependencies>
  </dependencyManagement>
  <build>
    <finalName>celements-web</finalName>
    <plugins>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-war-plugin</artifactId>
        <configuration>
          <overlays>
            <overlay>
              <groupId>com.celements</groupId>
              <artifactId>tinymce-langs</artifactId>
              <excludes>
                <exclude>resources/celRTE/plugins/advimage</exclude>
              </excludes>
            </overlay>
            <overlay>
              <groupId>com.celements</groupId>
              <artifactId>image-web</artifactId>
              <excludes>
                <exclude>WEB-INF/lib/xml-apis-*.jar</exclude>
              </excludes>
            </overlay>
          </overlays>
        </configuration>
      </plugin>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-surefire-plugin</artifactId>
      </plugin>
      <plugin>
        <groupId>com.github.eirslett</groupId>
        <artifactId>frontend-maven-plugin</artifactId>
      </plugin>
      <plugin>
        <groupId>com.jarslab.maven</groupId>
        <artifactId>babel-maven-plugin</artifactId>
      </plugin>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-enforcer-plugin</artifactId>
        <executions>
          <execution>
            <id>enforce-dependency-convergence</id>
            <goals>
              <goal>enforce</goal>
            </goals>
            <configuration>
              <rules>
                <DependencyConvergence />
              </rules>
              <fail>true</fail>
            </configuration>
          </execution>
        </executions>
      </plugin>
      <plugin>
        <groupId>com.diffplug.spotless</groupId>
        <artifactId>spotless-maven-plugin</artifactId>
        <version>2.44.3</version>
        <configuration>
          <formats>
            <format>
              <includes>
                <include>**/*.xml</include>
                <include>**/*.xsd</include>
                <include>**/*.xsl</include>
                <include>**/*.xslt</include>
              </includes>
              <excludes>
                <exclude>src/main/webapp/docs/**/*.xml</exclude>
                <exclude>**/target/**</exclude>
                <exclude>**/node_modules/**</exclude>
              </excludes>
              <toggleOffOn />
              <eclipseWtp>
                <type>XML</type>
                <files>
                  <file>${project.basedir}/xml.prefs</file>
                </files>
              </eclipseWtp>
            </format>
          </formats>
        </configuration>
      </plugin>
    </plugins>
  </build>
</project>
