<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
  <parent>
    <groupId>com.celements</groupId>
    <artifactId>celements-parent</artifactId>
    <version>7.1-SNAPSHOT</version>
  </parent>
  <modelVersion>4.0.0</modelVersion>
  <url>https://github.com/celements/celements-web</url>
  <artifactId>celements-web-component</artifactId>
  <version>7.1-SNAPSHOT</version>
  <description>Celements Web Component</description>
  <dependencies>
    <dependency>
      <groupId>com.celements</groupId>
      <artifactId>celements-model</artifactId>
      <scope>provided</scope>
    </dependency>
    <dependency>
      <groupId>com.celements</groupId>
      <artifactId>celements-spring-security</artifactId>
      <scope>provided</scope>
    </dependency>
    <dependency>
      <groupId>com.celements</groupId>
      <artifactId>celements-xwiki-core</artifactId>
      <scope>provided</scope>
    </dependency>
    <dependency>
      <groupId>com.celements</groupId>
      <artifactId>celements-observation</artifactId>
      <scope>provided</scope>
    </dependency>
    <dependency>
      <groupId>com.celements</groupId>
      <artifactId>celements-xwiki-velocity</artifactId>
      <scope>provided</scope>
    </dependency>
    <dependency>
      <groupId>com.celements</groupId>
      <artifactId>celements-core</artifactId>
      <scope>provided</scope>
    </dependency>
    <dependency>
      <groupId>org.springframework</groupId>
      <artifactId>spring-context</artifactId>
      <scope>provided</scope>
    </dependency>
    <dependency>
      <groupId>org.springframework</groupId>
      <artifactId>spring-web</artifactId>
      <scope>provided</scope>
    </dependency>
    <dependency>
      <groupId>org.springframework</groupId>
      <artifactId>spring-webmvc</artifactId>
      <scope>provided</scope>
    </dependency>
    <dependency>
      <groupId>javax.inject</groupId>
      <artifactId>javax.inject</artifactId>
    </dependency>
    <dependency>
      <groupId>javax.servlet</groupId>
      <artifactId>javax.servlet-api</artifactId>
      <scope>provided</scope>
    </dependency>
    <dependency>
      <groupId>com.celements</groupId>
      <artifactId>celements-shared-tests</artifactId>
      <scope>test</scope>
    </dependency>
  </dependencies>
  <scm>
    <connection>scm:git:git://github.com/celements/celements-web</connection>
    <developerConnection>scm:git:git@github.com:celements/celements-web.git</developerConnection>
    <url>https://github.com/celements/celements-web</url>
    <tag>HEAD</tag>
  </scm>
</project>
